### ISSUE TITLE
"command" option is empty.

### ISSUE THREAD

**Issue by okapixel** [thinca/vim-quickrun#116]
上記エラーが出て実行できません。原因は何でしょうか。
:set filetype で filetype=cpp は確認済みです。

環境
Windows8.1 Kaoriya GVim7.4

![screenshot_2015-06-17-00-20-05](https://cloud.githubusercontent.com/assets/13287230/8634367/061e7198-2831-11e5-8d76-440e6a9b72d5.jpg)

**Comment by thinca** [comment]
C++ 言語をコンパイル/実行できる環境はあるでしょうか?

**Comment by okapixel** [comment]
大変失礼しました、パスが通っていませんでした
パスを通すとしっかり動作しました。素晴らしいプラグインをありがとうございます
