### ISSUE TITLE
引数入力時にコマンドプロンプトが起動し進まない

### ISSUE THREAD

**Issue by okapixel** [thinca/vim-quickrun#117]
Kaoriya版GVimでQuickrunを使用しています。

ソースコード入力後、
:Q -args 2
などで引数を指定してコンパイルすると、コマンドプロンプトが立ち上がります
どうやら引数を渡して処理しているようなのですが、問題はここで処理が止まってしまうことです
具体的には、コマンドプロンプト起動後、そのまま特に進みません。コマンドプロンプト上で引数を再度入力しEnterを押すと、GVimに戻り正常動作します。
しかし、引数を指定しているので、出来ればスムーズにGVim上のみで遷移が終わってほしいのですが、何か問題がございますでしょうか。

![screenshot_2015-06-17-00-20-05](https://cloud.githubusercontent.com/assets/13287230/8728922/fadeb608-2c22-11e5-8f43-33ad6a7f9b81.jpg)
この状態で止まります。引数を入力してEnterすると問題ありませんが、不便です

**Comment by thinca** [comment]
そのプログラムは標準入力を受け取るものではありませんか? もしそうであれば、代わりに `-input` オプションを使ってみてください。詳しくは help を見てください。

**Comment by thinca** [comment]
返事がないようであれば閉じます。

**Comment by okapixel** [comment]
失礼しました
無事解決しました。ありがとうございました
