### ISSUE TITLE
バッファのフラッシュ無しに、リアルタイムに出力を得る

### ISSUE THREAD

**Issue by kota65535** [thinca/vim-quickrun#127]
古い記事ですが、#46 でosyo-mangaさんの最後の返信にあるように

http://d.hatena.ne.jp/osyo-manga/20131112/1384255703#c1384690300

上記記事のコメント欄にて、実行プログラム側のバッファのフラッシュ無しに、リアルタイムに出力を得ることができるパッチをichizokさんが公開されていますが、こちらを取り込む予定は無いのでしょうか？
もしすでに議論済みでしたらすみません。

**Comment by thinca** [comment]
ありがとうございます。検討します。

**Comment by thinca** [comment]
最新版では job-runner を使った場合、`runner/job/pty` に 1 を渡すことで回避できます。
まだ問題があるようであれば再オープンしてください。
