### ISSUE TITLE
現在のバージョン？のscalaコマンドで実行すると何も出力されない

### ISSUE THREAD

**Issue by aiya000** [thinca/vim-quickrun#143]
# 問題
　以下のコード中で:QuickRunを実行しても、quickrunバッファに何も出力されない。

Test.scala
```scala
sealed abstract class Tree
case class Node(x: Int, left: Tree, right: Tree) extends Tree
case object Leaf extends Tree

object Test {
	val tree: Tree = Node(1
		, Node(2, Leaf, Leaf)
		, Node(3, Leaf, Leaf)
		)

	def main(args: Array[String]): Unit = {
		println("ahoge")
		println(tree)
	}
}
```

# 原因
　少なくとも私の環境のscalaコマンドだと、以下のコマンドを実行しても、標準出力に何も出力されない。

```console
$ ls
Test.scala
$ scala Test.scala
(no ouput)
```

# 私の環境
- ArchLinux
+ 公式リポジトリからインストールしたパッケージ
    - scala

```console
$ scala -version
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
```

- - -

　Scalaを始めたのが最近なので全然わからないですが、以前のscalaコマンドだと上記コマンドを実行するだけで出力がされたのかな？  
私の環境の問題(scalaのバージョン等)のせい？

**Comment by aiya000** [comment]
私の環境で確認できる限りのFixを[プルリクしておきました](https://github.com/thinca/vim-quickrun/pull/144)。
(filetype javaで起こる問題と同じものが起こってしまうけど…
 - Test.scalaのobject名がTest以外だとQuickRunできない
 - Test.class以外のclassファイルがカレントディレクトリに残る
)

**Comment by thinca** [comment]
Scala には一応 [script として実行するモード](http://www.scala-lang.org/documentation/getting-started.html#script-it)があり、コンパイルして実行させる設定を用意するのが Java 同様難しかったので、この方法でお茶を濁していました。
ただ、今改めて最新の Scala のドキュメントを見ると shebang を使うようにしているので、スクリプトモードは shenbang 使うようにしてコンパイルを標準にするほうが良さそうな気がしますね。

**Comment by aiya000** [comment]
:+1:
