### ISSUE TITLE
How to disable "hook/shebang"?

### ISSUE THREAD

**Issue by laxtiz** [thinca/vim-quickrun#146]
I write python code on windows.
if source code haven't shebang on line one, all ok.
but my code run on a linux server, there must have shebang line.

How to disable shebang module?
like this ?
```vimL
let g:quickrun_config = {}
let g:quickrun_config._ = {
            \ 'hook/shebang/enable': 0
            \ }
```

**Comment by thinca** [comment]
Yes.  Are there any problems?

**Comment by laxtiz** [comment]
no problems. thanks
i have changed like this:
```vimL
let g:quickrun_config = {}
let g:quickrun_config._ = {
            \ 'hook/shebang/enable': !has('win32')
            \ }
```
