### ISSUE TITLE
実行結果が左側に出てきてしまう

### ISSUE THREAD

**Issue by toshi0383** [thinca/vim-quickrun#157]
Buffer opens on left side. Why is this?

最初は実行結果は右側に出てたんですが、左側に出るようになってしまいました。助言いただけますと🙇
![quickrun-buffer-opens-on-left](https://user-images.githubusercontent.com/6007952/29768574-bcaf311c-8c21-11e7-8d88-57f5c8846cfb.gif)
macOSで、 `.vimrc` は以下の通りです。
```
set hlsearch
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent

" Pathogen
execute pathogen#infect()

filetype plugin indent on
syntax on
```

**Comment by shi-cong** [comment]
map <leader>r :QuickRun<CR>                                                                                                                    
 let g:quickrun_config = {                                                                                                                        
 \   "_" : {                                                                                                                                    
 \       "outputter" : "message",                                                                                                           
 \   },                                                                                                                                         
 \}                                                                                                                                             
                                                                                                                                                  
 let g:quickrun_no_default_key_mappings = 1

**Comment by thinca** [comment]
vimrc に

```
set splitright
```

と書いてみてください。

**Comment by toshi0383** [comment]
お、ありがとうございます。右側に出るようになりましたm
