### ISSUE TITLE
How to read user input values ? 

### ISSUE THREAD

**Issue by bpRsh** [thinca/vim-quickrun#174]
Let's say we have a python script to read two numbers from terminal:
```
#!python
# -*- coding: utf-8 -*-#
"""
Date   : May 23, 2018
"""
# Imports
import sys

print('Please enter two integers, separated by space')
x, y = list(map(int, sys.stdin.readline().split()))
```

How to run this command in vim-quickrun ?

**Comment by TornaxO7** [comment]
You have to use the `-input` flag. I have this shortcut:
```vim
:QuickRun -outputter loclist -hook/tim/enable 1 -input "="
```
If you want to put something into `stdin`, than you can add them behind the `=` like this:
```vim
:QuickRun -outputter loclist -hook/tim/enable 1 -input "=First Second Third"
```
and so on.

**Comment by thinca** [comment]
@TornaxO7 Thank you 😃 

@bpRsh 
Closing.  Please reopen if your question is not solved.
