### ISSUE TITLE
Outputter buffer additional adjustments possible?

### ISSUE THREAD

**Issue by koblihh** [thinca/vim-quickrun#177]
I would like to set the quickrun outputter buffer with `norelativenumber` and `nonumber`.

I have tried adding the following commands with no success, unfortunately.

```
augroup quickRunOutputBuffer
  autocmd!
  autocmd FileType quickrun setlocal norelativenumber nonumber 
  autocmd FileType qf setlocal norelativenumber nonumber 
augroup END

autocmd BufReadPost,BufNewFile quickrun setlocal nonumber nowrap
```

Any suggestions / help will be greatly appreciated!

**Comment by koblihh** [comment]
This is my current solution of the issue above.
```
augroup QuickRunTerminalOutputBuffer
  au!
  autocmd CursorMoved *
        \ if &buftype ==# 'terminal' |
        \  setl norelativenumber nonumber |
        \ endif
augroup END
```
I would greatly appreciate it to have your feedback / suggestions on improving the code.

**Comment by windowsrefund** [comment]
This didn't work for me but I found the following persists after running in the window once. Perhaps something about neovim?

:set nornu nonu nocuc nocul fdc=0
