### ISSUE TITLE
How to pass command line arguments to script being run?

### ISSUE THREAD

**Issue by windowsrefund** [thinca/vim-quickrun#187]
Similar to #174 but not trying to grab user input

**Comment by TornaxO7** [comment]
So what are you trying than? Try this command: `:h quickrun-option-input` it's probably that what you're looking for.

**Comment by thinca** [comment]
@TornaxO7 Thank you 😃 

@windowsrefund 
Also read `:h quickrun-option-args`.
Closing.  Please reopen if your question is not solved.
