### ISSUE TITLE
(help) error 117

### ISSUE THREAD

**Issue by 5c0tt-b0t** [thinca/vim-quickrun#204]
Hi, this seems great but I cannot get it to work.
### Test:
```bash
#!/bin/bash

ls -A
```
When I issue `:QuickRun` I get an error:
```vim
Error detected while processing function quickrun#command#execute[10]..quickrun#run[10]..108[13]..111[9]..38[19]..<SNR>83_execute_in_result_window:
line 2: E117: Unknown function: win_execute
```
Thank you for any help, its appreciated!

**Comment by thinca** [comment]
Your Vim is too old.  Please upgrade to latest version and try again.

**Comment by robre** [comment]
I am getting the same issue on neovim 0.4.4 (latest version). AFAIK there is no win_execute in neovim?

**Comment by robre** [comment]
so apparently support for `win_execute` was added _yesterday_ to neovim. Updating to the development branch of neovim fixed this error for me.

**Comment by 5c0tt-b0t** [comment]
sorry for the delayed response! yes, I am on the latest stable `neovim` (0.4.4), happy to hear `win_execute` was added, I will update like you said.

**Comment by thinca** [comment]
`outputter/buffer` was rewritten from scratch in v0.9.0, but the old version is available yet named `buffer_legacy`.
I updated in e5e83bfd613bd58aa6bbbfaaed2f7eef1ed0b378 to use `outputter/buffer_legacy` as default when Vim doesn't have `win_execute()`.
