### ISSUE TITLE
Magic output bufname opens duplicate output windows

### ISSUE THREAD

**Issue by bootleq** [thinca/vim-quickrun#205]
Hi, the changes in 70e760e seems no longer match bufname contains magic characters, for example
`:QuickRun -command 'ls' -outputter/buffer/bufname '[v]'`
fails finding opened output buffer (named `[v]`), thus lead to open second output.

Add a `\M` flag to the pattern might not satisfy all buffer names, but does help in my use case, do you think this solution ok? Thanks.
`return '^\M' . a:pat . '$'`

**Comment by thinca** [comment]
Thank you for the report.
Fixed https://github.com/thinca/vim-quickrun/commit/51406a16cd423dc5d0b3b9e21be7e7c5e9cd9c6a

**Comment by thinca** [comment]
The previous change was wrong in some situation.
I fixed again for this: https://github.com/thinca/vim-quickrun/commit/d8f476180cc5242f29852aa44825cd5de487a8ac
I believe this is finally fixed, but you can report if there are problems.
