### ISSUE TITLE
runnerがvimprocだとRをquickrunできない

### ISSUE THREAD

**Issue by ujihisa** [thinca/vim-quickrun#34]
autoload/quickrun.vim

    372 \ 'r': {
    373 \   'command': 'R',
    374 \   'exec': '%c %o --no-save --slave %a < %s',
    375 \ },

runnerがvimprocだとリダイレクトのつもりで使ってる<が引数とみなされてしまうぽいっです。

該当部分で対処するなら、'%c %o --no-save --slave %a < %s'を'sh -c "'%c %o --no-save --slave %a < %s'"'にすれば一応解決します。が、そもそもそこで対処するべきかどうかわからないので、どうでしょう。

**Comment by thinca** [comment]
@ujihisa これってまだ起きる感じでしょうか?

**Comment by ujihisa** [comment]
Rをアンインストールしたのでそのままでは試せないですが、いま試しに`QuickRun -runner vimproc -command cat -exec '%c -n < %s'`みたいなのやってみたところバッチリぽかったです。

vimproc修正++
