### ISSUE TITLE
How to set the size of quickrun's ouput window?

### ISSUE THREAD

**Issue by UncleBill** [thinca/vim-quickrun#60]
As the title.
The output window should be smaller: when vertical split,ouput window's slim in width,when horizontal split,output window shorter.

**Comment by karadaharu** [comment]
It's tooooo late but you can set the buffer window size by setting config on `.vimrc` as follows;

```
let g:quickrun_config = {
      \'*': {
      \'outputter/buffer/split': ':40vsplit'},}
```

if you want to split horizontally or change the width, please modify `'40vsplit'`.

Thanks!

**Comment by TornaxO7** [comment]
Shouldn't this issue be closed?
