### ISSUE TITLE
repl起動に15秒以上かかる環境が存在する

### ISSUE THREAD

**Issue by supermomonga** [thinca/vim-quickrun#89]
ので、process_managerなrunnerはそれを前提とした設計に変更する必要があるみたいです。

ujihisaさんの代わりに立てました。
http://lingr.com/room/vim/archives/2014/05/18#message-19055161

**Comment by ujihisa** [comment]
@supermomonga 最新版neoclojureなら2~4秒くらいでいけるはず

**Comment by supermomonga** [comment]
便利そう
